- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print couse information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, couse duration is  {{ DURATION }}, and Trainer is {{ TRAINER }}"